# NumPy is a Python library used for working with arrays.

In [2]:
import numpy as np

In [3]:
num = [2, 4, 5, 9, 8,3]
arr = np.array(num)                 #this method converts a list in an array

print(arr)

[2 4 5 9 8 3]


In [4]:
print(arr.dtype)                   # this method returns the data type of an array

int64


In [6]:
N = [6.5, 2.8, 9.0, 5.6, 4.3]
arr = np.array(N)
newarr = arr.astype('i')           #this method change one data type to another

print(newarr)
print(newarr.dtype)

[6 2 9 5 4]
int32


In [7]:
n = [5, 7, 8, 3, 4, 1]
C = n.copy()                       #this method make a copy of an array and can change copied data
n[1] = 10

print(n)
print(C)

[5, 10, 8, 3, 4, 1]
[5, 7, 8, 3, 4, 1]


In [9]:
n = np.array([5, 7, 8, 3, 4, 1])
C = n.view()                       #this method make a view of an array and can change the original data
n[1] = 20

print(n)
print(C)

[ 5 20  8  3  4  1]
[ 5 20  8  3  4  1]


In [10]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)                    #this attribute returns the shape of an array in numerical value


(2, 4)


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr1 = arr.reshape(4, 3)           #this method reshape the array from 1-D to 2-D 
newarr2 = arr.reshape(2,3,2)          #this method reshape the array from 1-D to 3-D

print("Reshaping 1-D array to 2-D array: ",newarr1)
print("Reshaping 1-D array to 3-D array: ",newarr2)


Reshaping 1-D array to 2-D array:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaping 1-D array to 3-D array:  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
